create schema if not exists public;

create table if not exists public.user_profiles (
    id bigint generated by default as identity primary key,
    issuer text not null,
    subject text not null,
    email text,
    profile_name text not null,
    payload jsonb not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (issuer, subject, profile_name)
);

create index if not exists idx_user_profiles_user
    on public.user_profiles (issuer, subject);
